// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
................................
.......................3...3....
3...3....3..3..3..3.....3.3.....
.3.3....3.3.33.3..3......3......
..3....3...33.33.3.3....3.3.....
.3.3..3.333.3..333333..3...3....
3...33......3..33....33.....3...
................................
................................
..........333.333...............
..........3...3.3...............
..........333.3.3...............
............3.3.3...............
..........333.333...............
................................
................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
